### ISSUE TITLE
Fish drop to the bottom of the ocean

### ISSUE THREAD

**Issue by Alainx277** [Globox1997/RpgZ#11]
This makes fishing quite annoying and unrealistic.

Maybe all mob corpses should float on water?

**Comment by Globox1997** [comment]
Added a config for it [https://github.com/Globox1997/RpgZ/commit/a375e60d28b337f94abc99ca2b38342b6e52fe5f](https://github.com/Globox1997/RpgZ/commit/a375e60d28b337f94abc99ca2b38342b6e52fe5f)
Did you request it for the fabric version?

**Comment by Alainx277** [comment]
Thanks for adding it!

Unfortunately we're still using Forge (because of other mods). Is it a lot of work to port it to the Forge version?

**Comment by Stereowalker** [comment]
This should now be a feature on the forge branch. If it isn't feel free to create a new issue
