### ISSUE TITLE
Player corpses

### ISSUE THREAD

**Issue by JollySquid** [Globox1997/RpgZ#12]
This is less of an issue and more of just a request, but I'm working on a PvPish modpack and I'd really like to have it as a config option to spawn player corpses. It might be a bit difficult to get it to load in player skins so if it's easier you could just have them be skeletons or something, but I'd really like the corpse logic to be consistent across mobs and players.

Thx lol

**Comment by Globox1997** [comment]
I made a mod called Revive which has the config option to allow to loot dead players, this might work for you

**Comment by NixityNull** [comment]
you could use this mod as a substitute if you are using forge https://www.curseforge.com/minecraft/mc-mods/corpse/files

**Comment by Globox1997** [comment]
With those options, we can close this issue
