### ISSUE TITLE
[Feature request] Destroy corpses on shift-right click 

### ISSUE THREAD

**Issue by mmmilord** [Globox1997/RpgZ#15]
Shift + right click on corpse will destroy it and the loot will fall to the ground
Option to have items go directly to the players inventory, if it can accept items. If there isn't enough space, it drops normally  instead

**Comment by Globox1997** [comment]
Done with [https://github.com/Globox1997/RpgZ/commit/79d12e47ce51c108585f876d117cb14c12fe65b2](https://github.com/Globox1997/RpgZ/commit/79d12e47ce51c108585f876d117cb14c12fe65b2)
Thanks for the idea :)

**Comment by mmmilord** [comment]
Hi, thanks for accepting the request. I see you added it on the latest version.
Is there still a possibility you might add it to the 1.16.5 forge version? Or is that no longer maintained. Thanks!

**Comment by Globox1997** [comment]
For the forge version of this mod is Stereowalker responsible, you could ping him :)

**Comment by mmmilord** [comment]
@Stereowalker  If you are still working on this project, then anytime you could implement this feature I would appreciate it :)

**Comment by Stereowalker** [comment]
Gotcha
