### ISSUE TITLE
Items duplicate when you crouch + right click the mob

### ISSUE THREAD

**Issue by vikenventures** [Globox1997/RpgZ#16]
Whenever my inventory is full, whenever I crouch + right-click the corpse, it will duplicate and drop the item inside the corpse every time I do it.

**Comment by Globox1997** [comment]
Do you play with the forge or fabric version of the mod? and which mod version do you use?

**Comment by vikenventures** [comment]
rpgz-0.4.10.jar for Fabric 1.17.1

**Comment by Globox1997** [comment]
Thanks for report, fixed with [https://github.com/Globox1997/RpgZ/commit/559d10f4b36036b93fe289175107c2e0346c21f0](https://github.com/Globox1997/RpgZ/commit/559d10f4b36036b93fe289175107c2e0346c21f0)
