### ISSUE TITLE
Unable to exclude Entities. 1.16.5 Forge.

### ISSUE THREAD

**Issue by FernoXL** [Globox1997/RpgZ#18]
[rpgz-0.4.5-forge](https://www.curseforge.com/minecraft/mc-mods/rpgz/files/3398905)

Failure to exclude entities when configured to do so.

`#Example: minecraft:zombie or adventurez.brown_fungus`
`excluded_entities = ["minecraft.zombie"]`

The Zombies still drop bodies. And this is also an issue for other mobs.

**Comment by Stereowalker** [comment]
Change it to `"minecraft:zombie"`. The example is incorrect. Use `:` as a separator not `.`

**Comment by Stereowalker** [comment]
@FernoXL
