### ISSUE TITLE
Mobs killed by fire continue to burn infinitely

### ISSUE THREAD

**Issue by RDKRACZ** [Globox1997/RpgZ#2]

**Comment by Globox1997** [comment]
gonna check this

**Comment by Globox1997** [comment]
Mh can't reproduce this bug, when does this happen?

**Comment by Globox1997** [comment]
every mob should stop burning after you killed them

**Comment by RDKRACZ** [comment]
I'm sure this was a thing. I saw this a few times but can't reproduce it now

**Comment by Globox1997** [comment]
was it a specific mob?

**Comment by RDKRACZ** [comment]
I think it was about all mobs

**Comment by Globox1997** [comment]
mh as long as we don't know when this happens, I don't see any way to fix it

**Comment by RDKRACZ** [comment]
I understand, I will close this issue and eventually reopen it if this will happen again. Thank You for responding, I'm opening issues daily and many devs are just ignoring them.

**Comment by Globox1997** [comment]
yea just reopen it again :) I don't think they ignore it.  Most of the time I say to myself "gonna check it later" and forget it xD

**Comment by RDKRACZ** [comment]
Yes, this is happening again.

![2020-12-31_14 31 06](https://user-images.githubusercontent.com/43277609/103412420-54bf1d80-4b75-11eb-930c-93eca25bb446.png)
![2020-12-31_14 33 35](https://user-images.githubusercontent.com/43277609/103412426-55f04a80-4b75-11eb-9590-7e89953b3dba.png)

**Comment by RDKRACZ** [comment]
And if I save the world and load it again all the bodies disappear.

**Comment by RDKRACZ** [comment]
Sometimes if a mob die the body isn't appearing.

**Comment by RDKRACZ** [comment]
Ok so it doesn't always happen and also (I'm not sure) there is a requirement - mob (creeper) must be on fire from the sun. This means it only happens when the mods like [Photoallergic Creepers](https://www.curseforge.com/minecraft/mc-mods/photoallergic-creepers) or [Fabrication](https://www.curseforge.com/minecraft/mc-mods/fabrication) (need to be manually turned on) are installed.

**Comment by Globox1997** [comment]
and no other mods are installed I guess?
yea the bodies won't save in the world and they disappear when the hitbox could stuck inside a block.
how did you set them on fire?

**Comment by RDKRACZ** [comment]
Well, I was checking with 200 other mods. I'm not setting the creepers on fire - the mods I mentioned are making creepers burn in the daylight like zombies and skeletons.

**Comment by RDKRACZ** [comment]
Okay so
It's not caused by these two mods mentioned earlier. It just happened with skeletons too.
![2021-01-03_13 48 37](https://user-images.githubusercontent.com/43277609/103478996-a3192a00-4dca-11eb-9efa-1907fde6638d.png)
![2021-01-03_13 49 01](https://user-images.githubusercontent.com/43277609/103478997-a44a5700-4dca-11eb-92d4-e7ab085ba488.png)

**Comment by RDKRACZ** [comment]
Also can you make them to not fly? On the ss they are barely touching any blocks
![2021-01-03_13 52 31](https://user-images.githubusercontent.com/43277609/103479053-158a0a00-4dcb-11eb-9a13-02d57ac5e141.png)

**Comment by RDKRACZ** [comment]
Lol
![2021-01-03_14 08 21](https://user-images.githubusercontent.com/43277609/103479308-28054300-4dcd-11eb-860f-68dec5deaa28.png)

**Comment by Globox1997** [comment]
Uploaded a fixed version, should be approved tomorrow

**Comment by Globox1997** [comment]
does the new version fix it?

**Comment by RDKRACZ** [comment]
I think so but I only played maybe half an hour (testing other mods) in the week so I'm not sure. I will reopen if needed.
