### ISSUE TITLE
Modded mobs doesnt drop 100% time loot?

### ISSUE THREAD

**Issue by TheButterbrotMan** [Globox1997/RpgZ#21]
This does seem to be a problem relating to the Corpse mod (Rpgz), and it seems to effect modded entities in that they dont seem to drop a corpse 100% of the time

**Comment by TheButterbrotMan** [comment]
https://github.com/TheButterbrotMan/Deathdusk/issues/55

**Comment by Stereowalker** [comment]
Is this a forge specific problem?

**Comment by TheButterbrotMan** [comment]
No. I experiencing this problem on fabric.

**Comment by Globox1997** [comment]
Which mob for example doesn't drop sometimes?

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/RpgZ/commit/1d37df84c7844e0aa8072d8a6f7a5513e0d22781](https://github.com/Globox1997/RpgZ/commit/1d37df84c7844e0aa8072d8a6f7a5513e0d22781)
