### ISSUE TITLE
rpgz.json5 Auto Reset in server

### ISSUE THREAD

**Issue by SvCpu** [Globox1997/RpgZ#22]
server: fabric 1.18.2
issue:
Automatically reset the configuration file rpgz.json5 when the server is started(Only excluded_entities are reset)
So I can't configure rpgz on the server
original:
	"excluded_entities": [
		"minecraft:shulker",
		"bosses_of_mass_destruction:void_blossom"
	]
reset:
	"excluded_entities": [
		"minecraft:shulker"
	]
Or is it a problem with my configuration?

**Comment by cristiandp** [comment]
server: fabric 1.19
It occurs the same, no mater the way you configure it, directly in the file or by config buttom in mod's list section

**Comment by Globox1997** [comment]
Changed list type with [https://github.com/Globox1997/RpgZ/commit/24197e378bfe5ca717ab126192d3fc8562cd4cd0](https://github.com/Globox1997/RpgZ/commit/24197e378bfe5ca717ab126192d3fc8562cd4cd0)
I hope this will fix the issue

**Comment by Globox1997** [comment]
Fixed with the latest update
