### ISSUE TITLE
[Suggestion] Using a Shovel

### ISSUE THREAD

**Issue by FernoXL** [Globox1997/RpgZ#23]
Can I request that shovels be used to remove the corpses of mobs automatically? 
This is for when you set them to not automatically despawn after being looted there would be a way to remove the corpses without waiting for the timer/countdown.

**Comment by Globox1997** [comment]
Added with [https://github.com/Globox1997/RpgZ/commit/d69f47f1521f50fd20047ae3266571ecf35160d7](https://github.com/Globox1997/RpgZ/commit/d69f47f1521f50fd20047ae3266571ecf35160d7)

**Comment by FernoXL** [comment]
Thank You.
I would also like to ask if this could be added to 1.18.2 Fabric and Forge. I'm unsure if you are still supporting older versions but it would be really appreciated.

**Comment by Globox1997** [comment]
At least for the fabric side, I only work on the latest version of my mods
