### ISSUE TITLE
[Request] Can you make it so that mob corpses doesn't actually trigger the message "There are monsters nearby." Thanks!

### ISSUE THREAD

**Issue by cymophic** [Globox1997/RpgZ#24]

**Comment by Stereowalker** [comment]
I'll try my best to fix that on Forge

**Comment by cymophic** [comment]
Thanks! Please do so for fabric as well!

**Comment by Globox1997** [comment]
Fixed in fabric version with [https://github.com/Globox1997/RpgZ/commit/b333b7e80e7e3cc458ec840b25f9c58edca4f11f](https://github.com/Globox1997/RpgZ/commit/b333b7e80e7e3cc458ec840b25f9c58edca4f11f)
