### ISSUE TITLE
Can't mantain custom list of excluded entities after server start

### ISSUE THREAD

**Issue by HOLYSPAGETI** [Globox1997/RpgZ#29]
Every time I make changes to the excluded entities list and restart the server to apply them, the portion of the config file about entities blacklist resets to default having "minecraft:shulker" as the solely entity blacklisted.

Hereunder I paste the config file text after I have changed it and after I have restarted the server. Note that the "hopper_extracting" parameter manteined the setting set to "true" (default is false).

{
	"drop_unlooted": false,
	"hopper_extracting": true,
	// Default: 2400ticks = 2min
	"drop_after_ticks": 2400,
	"despawn_corps_after_ticks": 4800,
	"despawn_immediately_when_empty": true,
	"surfacing_in_water": true,
	// Example: minecraft:zombie or adventurez:brown_fungus
	"excluded_entities": [
		"minecraft:shulker"
	]
}

This happens even if I simply replace the already blacklisted entity with another, like:

{
	"drop_unlooted": false,
	"hopper_extracting": true,
	// Default: 2400ticks = 2min
	"drop_after_ticks": 2400,
	"despawn_corps_after_ticks": 4800,
	"despawn_immediately_when_empty": true,
	"surfacing_in_water": true,
	// Example: minecraft:zombie or adventurez:brown_fungus
	"excluded_entities": [
		"minecraft:zombie"
	]
}

**Comment by HOLYSPAGETI** [comment]
(forge 1.18.2)

**Comment by Globox1997** [comment]
Om fabrics side it was due to the use of the jankson serializer

**Comment by SergGrey** [comment]
> Om fabrics side it was due to the use of the jankson serializer

Hello, I saw that you fixed this problem for fabric(https://github.com/Globox1997/RpgZ/commit/24197e378bfe5ca717ab126192d3fc8562cd4cd0). Can you please make this fix in the 1.18.2 forge version? And it seems to me that the mod does not allow another mod(https://www.curseforge.com/minecraft/mc-mods/butchercraft) to replace the loot from the mobs.

**Comment by Stereowalker** [comment]
I'll try to have it fixed by tomorrow, but no promises on the time. I'm still trying to sort myself out

**Comment by SergGrey** [comment]
> I'll try to have it fixed by tomorrow, but no promises on the time. I'm still trying to sort myself out

Thank you in advance. And I hope everything is going great for you!

**Comment by Stereowalker** [comment]
I've uploaded it to CurseForge. With that, your issue should be addressed

**Comment by Stereowalker** [comment]
As this issue has been resolved, I'm closing this
