### ISSUE TITLE
Jockey glitch

### ISSUE THREAD

**Issue by KaykenJr** [Globox1997/RpgZ#31]
### Minecraft Version

1.19.x

### Mod Loader Version

Forge 43.2.0

### Mod Version

rpgz-0.5.3-forge.jar

### Describe the Issue

when killing the mounts of mounted mobs the mobs on the mounts say mounted and don't get kicked out.
![2023-06-22_21 57 22](https://github.com/Globox1997/RpgZ/assets/112353962/03f53c65-ba9c-4b30-bc70-82dcf65c17f2)

### latest.log

.

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/RpgZ/commit/f4e918b99f2609ab149de2b9d329a27c20777de4](https://github.com/Globox1997/RpgZ/commit/f4e918b99f2609ab149de2b9d329a27c20777de4)
