### ISSUE TITLE
eldritch mobs dont drop any loot

### ISSUE THREAD

**Issue by owleague** [Globox1997/RpgZ#33]
### Minecraft Version

1.19.x

### Mod Loader Version

Fabric 0.14.21

### Mod Version

0.5.3

### Describe the Issue

when killing an elite, ultra or eldritch mob their bodies despawn immediately with no loot and when it doesnt despawn they only have flesh or their normal mob loot instead of the bonus loot applied from the mod

### latest.log

N/A

### Do you use any other mods except the required ones?

eldritch-mobs-1.12.11

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/RpgZ/commit/1d37df84c7844e0aa8072d8a6f7a5513e0d22781](https://github.com/Globox1997/RpgZ/commit/1d37df84c7844e0aa8072d8a6f7a5513e0d22781)
