### ISSUE TITLE
Dismount entities riding killed entity

### ISSUE THREAD

**Issue by GitUser14975** [Globox1997/RpgZ#34]
### Make sure you are not opening a duplicate.

- [x] I have searched the issue tracker and did not find an issue describing my bug.

### Description of your suggestion.

So currently if you have a rideable entity like a skeleton horse and another entity like a skeleton is riding it, and then you kill the skeleton horse, it lays on the floor ready to be looted while the skeleton (entity that mounts the dead one) is stuck sitting above it. Maybe it should be automatically dismounted?

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/RpgZ/commit/f4e918b99f2609ab149de2b9d329a27c20777de4](https://github.com/Globox1997/RpgZ/commit/f4e918b99f2609ab149de2b9d329a27c20777de4)
