### ISSUE TITLE
Zombies dropping Chest on their loot table.

### ISSUE THREAD

**Issue by makumaku1974** [Globox1997/RpgZ#35]
### Make sure you are not opening a duplicate.

- [ ] I have searched the issue tracker and did not find an issue describing my bug.

### Description of your suggestion.

Idk why or how but it doesn't feel right to put chest randomly on any mobs. Is this a bug or a somewhat feature?

**Comment by Globox1997** [comment]
Does this happen when only this mod is installed?

**Comment by Globox1997** [comment]
RpgZ does not add equipment to mobs. If the mob has equipment (vanilla sometimes adds a shovel in the hand of a zombie for example) than there is a vanilla chance to drop it which will then get set to the inventory.
