### ISSUE TITLE
Doesn't work with SpoiledZ

### ISSUE THREAD

**Issue by Answordy** [Globox1997/RpgZ#39]
### Minecraft Version

1.19.x

### Mod Loader Version

0.14.22

### Mod Version

0.5.3

### Describe the Issue

On 1.19.2 animals drop non spoiling food, no nbt data. If I exclude them from rpgz they drop spoiling food again.

### latest.log

compat

**Comment by Globox1997** [comment]
Added compat with [https://github.com/Globox1997/RpgZ/commit/10e6d8f013f90a85ad9e0404834f3c9677f259d5](https://github.com/Globox1997/RpgZ/commit/10e6d8f013f90a85ad9e0404834f3c9677f259d5)
Out of time reasons I only work on the latest versions of my mods.
