### ISSUE TITLE
[Crash] Crashes with Pehkui installed.

### ISSUE THREAD

**Issue by MidasMischief** [Globox1997/RpgZ#41]
Granted I'm using Forge 1.20.1 using Sinytra Connector, I have no clue if this issue is present for the fabric version of Pehkui but I figured I'd make a post here anyways. The mod works great on Sinytra when Pehkui is not installed though!

**Comment by DeshiDesu** [comment]
Indeed this mod does crash when installed alongside Pekhui on Fabric 1.20.1

`[14/12/2023 03:32:58 a.m.] [main/ERROR] Mixin apply for mod pehkui failed pehkui.mixins.json:MobEntityMixin from mod pehkui -> net.minecraft.class_1308: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/class_1308::pehkui$tickMovement$expand$x with priority 1000 cannot inject into net/minecraft/class_1308::method_6007()V merged by net.rpgz.mixin.MobEntityMixin with priority 1000 [PREINJECT Applicator Phase -> pehkui.mixins.json:MobEntityMixin from mod pehkui -> Prepare Injections ->  -> modify$hop000$pehkui$tickMovement$expand$x(D)D -> Prepare]
[14/12/2023 03:32:58 a.m.] 	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)`

**Comment by DogeKingChris** [comment]
Yep, me too!

[latest.log](https://github.com/Globox1997/RpgZ/files/14831651/latest.log)

**Comment by Poopooracoocoo** [comment]
https://github.com/Virtuoel/Pehkui/issues/482#issuecomment-2016881422

**Comment by Globox1997** [comment]
Should be fixed with [https://github.com/Globox1997/RpgZ/commit/6a4bfad38554b3beeea5d5ee1bac396b5b79e404](https://github.com/Globox1997/RpgZ/commit/6a4bfad38554b3beeea5d5ee1bac396b5b79e404)
