### ISSUE TITLE
Crash on enchant command

### ISSUE THREAD

**Issue by kittech0** [Globox1997/RpgZ#46]
### Minecraft Version

1.20.x

### Mod Loader Version

0.15.10

### Mod Version

0.6.0

### Describe the Issue

When running `/enchant @s minecraft:power 5` the game crashes

### latest.log

https://mclo.gs/pSWoNaS

**Comment by Globox1997** [comment]
Probably fixed with [https://github.com/Globox1997/RpgZ/commit/6a4bfad38554b3beeea5d5ee1bac396b5b79e404](https://github.com/Globox1997/RpgZ/commit/6a4bfad38554b3beeea5d5ee1bac396b5b79e404)
