### ISSUE TITLE
Error on openning container

### ISSUE THREAD

**Issue by kittech0** [Globox1997/RpgZ#47]
### Minecraft Version

1.20.x

### Mod Loader Version

1.15.10

### Mod Version

0.15.10

### Describe the Issue

The issue was reported by one of the players of my modpack

### latest.log

https://cdn.discordapp.com/attachments/1040905595957547068/1236659667019632691/message-1.txt

### Do you use any other mods except the required ones?

Yes, it is modpack, can be found on https://github.com/kittech0/comely-adventure

**Comment by Globox1997** [comment]
Might be fixed with [https://github.com/Globox1997/RpgZ/commit/6a4bfad38554b3beeea5d5ee1bac396b5b79e404](https://github.com/Globox1997/RpgZ/commit/6a4bfad38554b3beeea5d5ee1bac396b5b79e404)
