### ISSUE TITLE
error

### ISSUE THREAD

**Issue by zc1108aaa** [Globox1997/RpgZ#48]
### Minecraft Version

1.20.x

### Mod Loader Version

0.15.11

### Mod Version

0,6,0

### Describe the Issue

[latest.log](https://github.com/user-attachments/files/15507604/latest.log)

### latest.log

1

**Comment by zc1108aaa** [comment]
Pehkui conflict rpgz
https://github.com/MehVahdJukaar/Randomium/issues/34

**Comment by zc1108aaa** [comment]
Pehkui conflict rpgz
https://github.com/MehVahdJukaar/Randomium/issues/34

**Comment by Globox1997** [comment]
Should be fixed with [https://github.com/Globox1997/RpgZ/commit/6a4bfad38554b3beeea5d5ee1bac396b5b79e404](https://github.com/Globox1997/RpgZ/commit/6a4bfad38554b3beeea5d5ee1bac396b5b79e404)
