### ISSUE TITLE
Villagers doesn't pick up items

### ISSUE THREAD

**Issue by Primeradude92** [Globox1997/RpgZ#49]
### Minecraft Version

1.20.x

### Mod Loader Version

0 .15.11

### Mod Version

0.6.0

### Describe the Issue

When using this mod, villagers stare at food items and attempt to pick them up, but never ends up actually picking them up. Happens on server & singleplayer. Villager proffesion doesn't matter.

I've tested the mod alone. +dependencies

Fabric API v.0.92.2
LibZ v.1.0.3
Cloth Config v.11.1.118

I've never failed to reproduce the problem.

### latest.log

[latest.log](https://github.com/user-attachments/files/15857315/latest.log)

**Comment by Givonbyte** [comment]
I have the same problem, mob griefing is set to "true" so thats not the issue, i like this mod, but it does'nt allow me or my villagers to pick up food to reproduce. It only works when i uninstalled the "RpgZ" mod (i have over 30 mods lmao)

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/RpgZ/commit/6a4bfad38554b3beeea5d5ee1bac396b5b79e404](https://github.com/Globox1997/RpgZ/commit/6a4bfad38554b3beeea5d5ee1bac396b5b79e404)
