### ISSUE TITLE
Update/Backport to 1.20.4

### ISSUE THREAD

**Issue by Jack-Chronicle** [Globox1997/RpgZ#50]
### Minecraft Version

1.20.x

### Mod Loader Version

0.15.11

### Mod Version

0.6.0

### Describe the Issue

Game crashes on launch when using 1.20.4 minecraft

### latest.log

[latest.log](https://github.com/user-attachments/files/15961304/latest.log)

**Comment by Globox1997** [comment]
Please update to the 1.21 version. Out of time reasons I only work on the latest version of my mods.
