### ISSUE TITLE
1.21 Corpse - Hopper Issues | Lithium involved

### ISSUE THREAD

**Issue by DarkFighter5000** [Globox1997/RpgZ#51]
### Minecraft Version

1.21.x

### Mod Loader Version

0.15.11

### Mod Version

0.6.0

### Describe the Issue

Hoppers don't pick up items from corpses when Lithium (0.12.7) is installed. (Yes the config was enagbled.) The mod is part of a custom modpack so it was a little tricky to pinpoint the issue but I could replicate the issue with just RpgZ (0.6.0) and Lithium (0.12.7) on a seperate instance (Fabric 0.15.11). Other mods used: Sodium 0.5.11, Cloth Config API 15.0.127, Fabric API 0.100.4, Text Placeholder API 2.4.0, Mod Menu 11.0.1.

With all these mods except Lithium the hoppers worked just fine on the corpses, but when I added Lithium (and only Lithium) it stopped working. As if the config had been simply disabled.

![Hoppers Don't Pull Loot From Corpses](https://github.com/Globox1997/RpgZ/assets/167707189/97f6a02e-ddff-47ba-a1e6-1f6ac21b0cf9)
An interesting observation I had while testing it (Lithium installed) is that sometimes a random hopper would take some loot from a corpse but only once out of hundreds. Not sure what the cause was, it happend while I was trying to kill mobs above the hoppers on a 1 block thick layer then dropping the corpse onto the hopper.

![Single Body Gets Stuck](https://github.com/Globox1997/RpgZ/assets/167707189/edc9b8e3-4d65-43e2-b9bc-a07ead5b3437)
Also sometimes (without Lithium) a corpse would - I assume - spawn in in a way that the hopper wouldn't see it and just ignore a random body sitting on it but still work on the others around it. This was also a rare exception, about 1 in a hundred, maybe even more.

### latest.log

-

### Do you use any other mods except the required ones?

Lithium

**Comment by Globox1997** [comment]
Should be fixed with [https://github.com/Globox1997/RpgZ/commit/6a4bfad38554b3beeea5d5ee1bac396b5b79e404](https://github.com/Globox1997/RpgZ/commit/6a4bfad38554b3beeea5d5ee1bac396b5b79e404)
