### ISSUE TITLE
excluded_entities not working

### ISSUE THREAD

**Issue by 100won-e** [Globox1997/RpgZ#52]
### Minecraft Version

1.20.x

### Mod Loader Version

0.15.11

### Mod Version

0.6.0

### Describe the Issue

Please understand that I am using a translator.
It is being used on the server, but the exclusion list does not work.
Config has been modified well.

First of all, shulkers are excluded by default.
Confirmed in single game.
Below is a photo from the single.

Also submit the config used by your server.
Please confirm

![image](https://github.com/user-attachments/assets/d434ddf9-7f06-4d9e-9d68-3c0b76e2b716)

{
  "drop_unlooted": true,
  "hopper_extracting": true,
  "drop_after_ticks": 1200,
  
  "despawn_corps_after_ticks": 2400,
  "despawn_immediately_when_empty": true,
  "surfacing_in_water": true,
  "excluded_entities": [
    "minecraft:shulker",
    "minecraft:blaze",
    "minecraft:magma_cube"
  ]
}
</details>

### latest.log

https://gist.github.com/100won-e/0d397d9a43173a1ee9f461a6351a1581

### Do you use any other mods except the required ones?

yes

**Comment by Globox1997** [comment]
maybe try a . instead of a : in the config.
