### ISSUE TITLE
Add new feature for NPCs to pick up items? - My Villagers UNABLE  PICK UP ITEMS/FOOD, thus they are unable to reproduce.

### ISSUE THREAD

**Issue by Givonbyte** [Globox1997/RpgZ#56]
### Make sure you are not opening a duplicate.

- [ ] I have searched the issue tracker and did not find an issue describing my bug/feature.

### Description of your suggestion.

Hi i have over 30 mods in MC and my problems was that my villagers could'nt pick up any food when  i was attempting do grow the village. Mob griefing is set to "true" so thats not the issue, and i see that this issue is allready on this forum, but it might just be how the mod is;

So i ask if there's a way to add the feature of mobs picking up items from the floor (maybe they need to have a inventory or something). So that villagers can reproduce.

The only way i solved this is by uninstalling RpgZ. 

Thanks for reading!

Have a nice day.

**Comment by Globox1997** [comment]
Forge or fabric?
This mod should not change the way villagers work.

**Comment by NoThrottle** [comment]
I can confirm, villagers (and every other mob) are unable to pick up items. This happens with the mod in isolation on my server too. Villagers can't pick up food, Zombies can't pick up dropped armor pieces, etc.

Fabric 1.20.1

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/RpgZ/commit/6a4bfad38554b3beeea5d5ee1bac396b5b79e404](https://github.com/Globox1997/RpgZ/commit/6a4bfad38554b3beeea5d5ee1bac396b5b79e404)
