### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by GitUser14975** [Globox1997/RpgZ#57]
### Minecraft Version

1.21.x

### Mod Loader Version

0.16.0

### Mod Version

0.6.0

### Describe the Issue

When I try to start the game, it crashes before it launches.
The game crashed whilst bootstrap
Error: java.lang.ExceptionInInitializerError

### latest.log

[latest.log](https://github.com/user-attachments/files/16551686/latest.log)

### Do you use any other mods except the required ones?

Yes, the issue happens only with the mods I'm playing with. It doesn't happen when RpgZ is used on its own.

**Comment by Globox1997** [comment]
Should be fixed with [https://github.com/Globox1997/RpgZ/commit/6a4bfad38554b3beeea5d5ee1bac396b5b79e404](https://github.com/Globox1997/RpgZ/commit/6a4bfad38554b3beeea5d5ee1bac396b5b79e404)
