### ISSUE TITLE
Sheep doesn't produce wool on death

### ISSUE THREAD

**Issue by JayCeeCreates** [Globox1997/RpgZ#6]
Everytime I kill a sheep, it just won't give me wool.

Tried unloading any mods, resource packs and datapacks, and nothing seems to happen. Sheep still wouldn't produce wool.

A fix would be appreciated.

**Comment by Globox1997** [comment]
uff this definitely needs a fix ;)

**Comment by Globox1997** [comment]
[rpgz-0.4.4, need to unzip.zip](https://github.com/Globox1997/RpgZ/files/5973811/rpgz-0.4.4.need.to.unzip.zip)
please try it out :)

**Comment by Globox1997** [comment]
this is for the fabric mod launcher btw

**Comment by JayCeeCreates** [comment]
Fixed! Thanks~
